<a href="https://colab.research.google.com/github/VoorugondaAnushka/2303A51176_B29_PDS/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

test_scores = np.random.randint(50, 101, size=(4, 4))
print(test_scores)

[[73 57 72 78]
 [90 75 65 67]
 [71 99 59 59]
 [53 56 78 67]]


In [13]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

Column-wise means: [71.75 71.75 68.5  67.75]
Row-wise means: [70.   74.25 72.   63.5 ]


In [14]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 12.111300250179582
Variance: 146.68359375


In [15]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 53
Maximum value: 99
Index of minimum value: 12
Index of maximum value: 9


In [17]:
print("Statistical Analysis Summary:")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [70.   74.25 72.   63.5 ]
Column-wise means: [71.75 71.75 68.5  67.75]
Overall Standard Deviation: 12.111300250179582
Overall Variance: 146.68359375
Global Minimum Value: 53 (Index: 12)
Global Maximum Value: 99 (Index: 9)


In [18]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[  6 200 212]
  [103 244   3]
  [130 197 238]]

 [[ 90 216 200]
  [ 24  29 130]
  [219 167  99]]

 [[208  42 234]
  [186 158  73]
  [ 85 123 158]]]


In [19]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[  6 103 130]
 [ 90  24 219]
 [208 186  85]]
Green Channel:
 [[200 244 197]
 [216  29 167]
 [ 42 158 123]]
Blue Channel:
 [[212   3 238]
 [200 130  99]
 [234  73 158]]


In [20]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 116.77777777777777
Average pixel intensity for Green channel: 152.88888888888889
Average pixel intensity for Blue channel: 149.66666666666666


In [21]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[ 56 250 255]
  [153 255  53]
  [180 247 255]]

 [[140 255 250]
  [ 74  79 180]
  [255 217 149]]

 [[255  92 255]
  [236 208 123]
  [135 173 208]]]


In [22]:
print("Statistical Analysis Summary:")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[  6 103 130]
 [ 90  24 219]
 [208 186  85]]
Green Channel:
 [[200 244 197]
 [216  29 167]
 [ 42 158 123]]
Blue Channel:
 [[212   3 238]
 [200 130  99]
 [234  73 158]]

Average pixel intensity for Red channel: 116.77777777777777
Average pixel intensity for Green channel: 152.88888888888889
Average pixel intensity for Blue channel: 149.66666666666666

Brightened Image (clipped at 255):
 [[[ 56 250 255]
  [153 255  53]
  [180 247 255]]

 [[140 255 250]
  [ 74  79 180]
  [255 217 149]]

 [[255  92 255]
  [236 208 123]
  [135 173 208]]]
